### ISSUE TITLE
Load model from local

### ISSUE THREAD

**Issue by shuai-dian** [lpiccinelli-eth/UniDepth#12]
I'm trying to load a model from local

```
from unidepth.models import UniDepthV1

with open("weights/config_v1_vitl14.json") as f:
    config = json.load(f)

model = UniDepthV1.build(config)
path = "/workspace/UniDepth/weights/unidepth_v1_vitl14.bin"
mod = torch.load(path)

info = model.load_state_dict(mod, strict=False)
```
But the following problem occurred，can you help me
```
Traceback (most recent call last):
  File "/workspace/UniDepth/demo.py", line 16, in <module>
    info = model.load_state_dict(mod, strict=False)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UniDepthV1:
        size mismatch for pixel_encoder.mask_token: copying a param with shape torch.Size([1, 1024]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.0.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([192]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.0.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([192]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.0.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 192]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.1.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.1.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.1.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 384]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.2.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.2.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.2.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 768]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.3.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.3.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.input_adapter.input_adapters.3.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.0.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.0.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.0.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.1.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.1.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.1.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.2.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.2.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.2.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1536]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.3.0.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.3.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pixel_decoder.token_adapter.input_adapters.3.1.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([512, 768]).
```

**Comment by lpiccinelli-eth** [comment]
It seems like the model built has ConvNext Large as the backbone, but the checkpoint downloaded has ViT-L as the backbone.

**Comment by lpiccinelli-eth** [comment]
I close the issue due to inactivity, if you have any more questions, feel free to reopen it!
