### ISSUE TITLE
TypeError: autotune() got an unexpected keyword argument 'use_cuda_graph'

### ISSUE THREAD

**Issue by CharlotteHao** [lpiccinelli-eth/UniDepth#84]
/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Traceback (most recent call last):
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/./scripts/demo.py", line 5, in <module>
    from unidepth.models import UniDepthV1, UniDepthV2
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/models/__init__.py", line 1, in <module>
    from .unidepthv1 import UniDepthV1
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/models/unidepthv1/__init__.py", line 1, in <module>
    from .unidepthv1 import UniDepthV1
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/models/unidepthv1/unidepthv1.py", line 17, in <module>
    from unidepth.models.unidepthv1.decoder import Decoder
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/models/unidepthv1/decoder.py", line 14, in <module>
    from unidepth.layers import (MLP, AttentionBlock, ConvUpsample, NystromBlock,
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/layers/__init__.py", line 5, in <module>
    from .nystrom_attention import NystromBlock
  File "/home/shahao/my_study/PF3plat/UniDepth/UniDepth/unidepth/layers/nystrom_attention.py", line 7, in <module>
    from xformers.components.attention import NystromAttention
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/components/__init__.py", line 15, in <module>
    from .attention import Attention, build_attention  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/components/attention/__init__.py", line 18, in <module>
    from ._sputnik_sparse import SparseCS
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/components/attention/_sputnik_sparse.py", line 9, in <module>
    from xformers.ops import masked_matmul
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import (
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/ops/fmha/triton_splitk.py", line 110, in <module>
    from ._triton.splitk_kernels import _fwd_kernel_splitK, _splitK_reduce
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/ops/fmha/_triton/splitk_kernels.py", line 632, in <module>
    _fwd_kernel_splitK_autotune[num_groups] = autotune_kernel(
                                              ^^^^^^^^^^^^^^^^
  File "/home/shahao/anaconda3/envs/Unidepth/lib/python3.11/site-packages/xformers/ops/fmha/_triton/splitk_kernels.py", line 614, in autotune_kernel
    kernel = triton.autotune(
             ^^^^^^^^^^^^^^^^
TypeError: autotune() got an unexpected keyword argument 'use_cuda_graph'

**Comment by CharlotteHao** [comment]
How to solve this problem？（Ask questions sincerely！！！
）

**Comment by zniihgnexy** [comment]
Hey i met the same error as you but i'm not sure your setting is the same as mine.

i split this into several small solutions:

1 cuda 124 not 118: it turns out that triton not supports cuda118 on windows
2 i changed "from xformers.components.attention import NystromAttention" into "from xformers.components.attention import *", probably there's ome structure difference and cause the error that couldn't find the location
3 i used triton 3.2.0 not 3.3.0

hope this could help you!
